/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package playlistApp;

/**
 *
 * @author joshm
 */
public class GUI extends javax.swing.JFrame {
    private musicManager musicManager;
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        musicManager = new musicManager();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl = new javax.swing.JLabel();
        exitBtn = new javax.swing.JButton();
        songNameInputLbl = new javax.swing.JLabel();
        songGenreInputLbl = new javax.swing.JLabel();
        addSongBtn = new javax.swing.JButton();
        likedSongsListLbl = new javax.swing.JLabel();
        songNameTxtField = new javax.swing.JTextField();
        playlist1Lbl = new javax.swing.JLabel();
        playlist2Lbl = new javax.swing.JLabel();
        likedSongsDisplayArea = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Playlist2DisplayArea = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        playlist1DisplayArea = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        numOfSongsBtn = new javax.swing.JButton();
        removeLastSongBtn = new javax.swing.JButton();
        removeAllSongsBtn = new javax.swing.JButton();
        moveLastSongBtn = new javax.swing.JButton();
        songNameTxtField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(0, 0, 0));
        titleLbl.setText("Music Manager");

        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        songNameInputLbl.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        songNameInputLbl.setForeground(new java.awt.Color(0, 0, 0));
        songNameInputLbl.setText("Song Name:");

        songGenreInputLbl.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        songGenreInputLbl.setForeground(new java.awt.Color(0, 0, 0));
        songGenreInputLbl.setText("Song Genre:");

        addSongBtn.setText("Add Song");
        addSongBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSongBtnActionPerformed(evt);
            }
        });

        likedSongsListLbl.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        likedSongsListLbl.setForeground(new java.awt.Color(0, 0, 0));
        likedSongsListLbl.setText("Liked Songs:");

        songNameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                songNameTxtFieldActionPerformed(evt);
            }
        });

        playlist1Lbl.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        playlist1Lbl.setForeground(new java.awt.Color(0, 0, 0));
        playlist1Lbl.setText("Playlist 1");

        playlist2Lbl.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        playlist2Lbl.setForeground(new java.awt.Color(0, 0, 0));
        playlist2Lbl.setText("Playlist 2");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        likedSongsDisplayArea.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        Playlist2DisplayArea.setViewportView(jTextArea2);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        playlist1DisplayArea.setViewportView(jTextArea3);

        numOfSongsBtn.setText("Number of Songs");
        numOfSongsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numOfSongsBtnActionPerformed(evt);
            }
        });

        removeLastSongBtn.setText("Remove Last Song");

        removeAllSongsBtn.setText("Remove All Songs");

        moveLastSongBtn.setText("Move Last Song");

        songNameTxtField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                songNameTxtField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(376, 376, 376)
                .addComponent(titleLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(removeAllSongsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(likedSongsListLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(songNameInputLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(songNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(likedSongsDisplayArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(songGenreInputLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(playlist1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(playlist1DisplayArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(removeLastSongBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(moveLastSongBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(songNameTxtField1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(numOfSongsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(playlist2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Playlist2DisplayArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(addSongBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLbl)
                    .addComponent(exitBtn))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(songNameInputLbl)
                    .addComponent(songGenreInputLbl))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(songNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(songNameTxtField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(likedSongsListLbl)
                            .addComponent(playlist1Lbl)
                            .addComponent(playlist2Lbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Playlist2DisplayArea)
                            .addComponent(likedSongsDisplayArea)
                            .addComponent(playlist1DisplayArea, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numOfSongsBtn)
                            .addComponent(removeLastSongBtn))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(removeAllSongsBtn)
                            .addComponent(moveLastSongBtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(addSongBtn)))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void addSongBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSongBtnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_addSongBtnActionPerformed

    private void songNameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_songNameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_songNameTxtFieldActionPerformed

    private void numOfSongsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numOfSongsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numOfSongsBtnActionPerformed

    private void songNameTxtField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_songNameTxtField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_songNameTxtField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Playlist2DisplayArea;
    private javax.swing.JButton addSongBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JScrollPane likedSongsDisplayArea;
    private javax.swing.JLabel likedSongsListLbl;
    private javax.swing.JButton moveLastSongBtn;
    private javax.swing.JButton numOfSongsBtn;
    private javax.swing.JScrollPane playlist1DisplayArea;
    private javax.swing.JLabel playlist1Lbl;
    private javax.swing.JLabel playlist2Lbl;
    private javax.swing.JButton removeAllSongsBtn;
    private javax.swing.JButton removeLastSongBtn;
    private javax.swing.JLabel songGenreInputLbl;
    private javax.swing.JLabel songNameInputLbl;
    private javax.swing.JTextField songNameTxtField;
    private javax.swing.JTextField songNameTxtField1;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
